#pragma once

#include <SDL2/SDL.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>

// A struct holding all standard Pywal colors clearly labeled
typedef struct {
    SDL_Color background;
    SDL_Color foreground;
    SDL_Color cursor;
    SDL_Color color0;  // Black
    SDL_Color color1;  // Red
    SDL_Color color2;  // Green
    SDL_Color color3;  // Yellow
    SDL_Color color4;  // Blue
    SDL_Color color5;  // Magenta
    SDL_Color color6;  // Cyan
    SDL_Color color7;  // White
    SDL_Color color8;  // Bright Black
    SDL_Color color9;  // Bright Red
    SDL_Color color10; // Bright Green
    SDL_Color color11; // Bright Yellow
    SDL_Color color12; // Bright Blue
    SDL_Color color13; // Bright Magenta
    SDL_Color color14; // Bright Cyan
    SDL_Color color15; // Bright White
} WalTheme;

// Helper to convert a raw hex string ("2E3440") to an SDL_Color
static inline SDL_Color WalParseHex(const char* hexStr) {
    SDL_Color color = {0, 0, 0, 255}; // Default to black, solid alpha
    if (!hexStr || *hexStr == '\0') return color;
    
    long val = strtol(hexStr, NULL, 16);
    color.r = (val >> 16) & 0xFF;
    color.g = (val >> 8) & 0xFF;
    color.b = val & 0xFF;
    return color;
}

// Parses the ~/.cache/wal/sdl_colors template generated by Pywal
static inline WalTheme WalLoadTheme(void) {
    WalTheme theme;
    memset(&theme, 0, sizeof(WalTheme)); // Default initialization
    
    const char* home = getenv("HOME");
    if (!home) return theme;
    
    char path[512];
    snprintf(path, sizeof(path), "%s/.cache/wal/sdl_colors", home);
    
    FILE* fp = fopen(path, "r");
    if (!fp) {
        fprintf(stderr, "wal.h: Could not open %s. Did you run pywal?\n", path);
        return theme;
    }
    
    // Array mapping loop indices directly to our struct properties
    SDL_Color* colors[] = {
        &theme.background, &theme.foreground, &theme.cursor,
        &theme.color0, &theme.color1, &theme.color2, &theme.color3,
        &theme.color4, &theme.color5, &theme.color6, &theme.color7,
        &theme.color8, &theme.color9, &theme.color10, &theme.color11,
        &theme.color12, &theme.color13, &theme.color14, &theme.color15
    };
    
    char line[16];
    int numColors = sizeof(colors) / sizeof(colors[0]);
    
    for (int i = 0; i < numColors; i++) {
        if (fgets(line, sizeof(line), fp)) {
            line[strcspn(line, "\r\n")] = 0; // Remove trailing newline
            *colors[i] = WalParseHex(line);
        }
    }
    
    fclose(fp);
    return theme;
}

// Checks if the Pywal cache file has been modified since we last checked
// Useful for live-updating the UI dynamically
static inline int WalHasThemeChanged(void) {
    static time_t last_mtime = 0;
    const char* home = getenv("HOME");
    if (!home) return 0;
    
    char path[512];
    snprintf(path, sizeof(path), "%s/.cache/wal/sdl_colors", home);
    
    struct stat attr;
    if (stat(path, &attr) == 0) {
        if (attr.st_mtime > last_mtime) {
            last_mtime = attr.st_mtime;
            return 1; // File updated!
        }
    }
    return 0;
}